### ISSUE TITLE
My Access Token does not save/persist

### ISSUE THREAD

**Issue by dylan-conlin** [Pro/put.io-firefox#4]
My Access Token does not save/persist. Do you have any ideas on how to make it save?

**Comment by Pro** [comment]
Do you mean in firefox?
Can you check if you have the following entries in your about:config:
![put io](https://f.cloud.github.com/assets/251973/2107757/2afa2e7a-8fd1-11e3-92f3-0ae45513f92d.PNG)

If not, please try to create them manually with the corresponding values

**Comment by dylan-conlin** [comment]
I added my access token to my about:config and everything's working now. Thank you. Would you like me to leave this issue open or close it?
