### ISSUE TITLE
firefox open magnet infinite loop

### ISSUE THREAD

**Issue by sejmann** [Pro/put.io-firefox#6]
I had to disable this plugin, because it intermittently opens unending new tabs for the magnet link selected.  Each new tab seems to open an identical new tab, ad infinitum.  Sometimes it works fine, other times it takes the browser down with it.

**Comment by Pro** [comment]
Was it a specific magnet link which ended in a loop or did it happen randomly?

**Comment by sejmann** [comment]
It seems my Firefox was somehow set as the default app handler for magnet links.  I believe this caused the occasional infinite loops.  I have no idea why it wasn't consistently a problem.  As soon as I found and removed the association, this plugin reliably behaves as designed.
